language: javascript
before_install: curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.1/install.sh | bash && nvm install v7.9
install: npm install
script: npm test
services:
  - redis-server