version: '3.7'
services:
  laundry:
    build: .
    image: registry.dev.sigapp.club/laundry/laundry-v2:latest
    restart: on-failure
    environment:
      REDIS_HOST: 'redis'
    ports:
      - "4502:80"
    depends_on:
      - redis
    deploy:
      replicas: 2
      update_config:
        delay: 1m
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "curl", "localhost/v2/status"]
      start_period: 30s
  redis:
    image: redis
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure